from __future__ import annotations

import argparse

from bubble_reconstruction.config import ReconstructionConfig
from bubble_reconstruction.fit_score import validate_existing_rotational_fit_score
from bubble_reconstruction.processing import run_pipeline


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Bubble 3D reconstruction runner. main.py only orchestrates the modular pipeline."
    )
    parser.add_argument("--dataset-dir", default="bubble.coco/train")
    parser.add_argument("--coco-file", default="_annotations.coco.json")
    parser.add_argument("--start-frame", type=int, default=100)
    parser.add_argument("--n-frames", type=int, default=10)

    parser.add_argument("--save-masks", action="store_true", help="Save original and rectified masks.")
    parser.add_argument("--save-point-clouds", action="store_true", help="Save reconstructed point clouds as PLY.")
    parser.add_argument("--no-preview", action="store_true", help="Disable the PyVista live preview window.")

    parser.add_argument("--diameter-mm", type=float, default=20.0)
    parser.add_argument("--voxel-mm", type=float, default=None)
    parser.add_argument("--smooth-sigma-z", type=float, default=2.0)
    parser.add_argument("--min-radius-vox", type=float, default=0.8)
    parser.add_argument("--min-area-cc", type=int, default=80)
    parser.add_argument("--iou-thr", type=float, default=0.15)

    parser.add_argument("--masks-dir", default="masks")
    parser.add_argument("--point-clouds-dir", default="point_clouds")
    parser.add_argument(
        "--annotate-frame-parameters",
        action="store_true",
        help="Save original frames with bubble IDs and calculated parameters drawn next to each bubble.",
    )
    parser.add_argument(
        "--annotated-frames-dir",
        default="annotated_frames",
        help="Output folder for frames generated by --annotate-frame-parameters.",
    )

    parser.add_argument(
        "--tracking",
        action="store_true",
        help="Track reconstructed bubbles frame-to-frame and save persistent track IDs.",
    )
    parser.add_argument(
        "--tracking-max-distance-mm",
        type=float,
        default=12.0,
        help="Maximum 3D centroid distance for assigning a bubble to an existing track.",
    )
    parser.add_argument(
        "--tracking-max-missing-frames",
        type=int,
        default=0,
        help="Frames a bubble may be missing before its track is closed. Default 0 closes immediately.",
    )
    parser.add_argument(
        "--tracking-labels",
        action="store_true",
        help="Show persistent track ID labels in the PyVista live preview.",
    )
    parser.add_argument(
        "--preview-parameter-labels",
        action="store_true",
        help="Show per-bubble parameter labels (ID, z, volume, e*, e_x, e_y) in the PyVista 3D preview.",
    )
    parser.add_argument(
        "--tracking-debug",
        action="store_true",
        help="Print detailed tracker matching diagnostics.",
    )
    parser.add_argument("--tracking-csv", default="tracking_parameters.csv")

    parser.add_argument(
        "--eccentricity",
        action="store_true",
        help="Calculate eccentricity and frame parameters for each processed frame.",
    )
    parser.add_argument("--parameters-dir", default="parameters")
    parser.add_argument("--tip-percentile", type=float, default=99.0)
    parser.add_argument(
        "--eccentricity-debug",
        action="store_true",
        help="Print detailed eccentricity diagnostics for each bubble.",
    )
    parser.add_argument(
        "--eccentricity-visualize",
        action="store_true",
        help="Show PyVista eccentricity visualization: full cloud gray, tip red, median point blue.",
    )
    parser.add_argument(
        "--eccentricity-visualize-every",
        type=int,
        default=1,
        help="Visualize eccentricity every Nth processed global frame. Default: 1.",
    )
    parser.add_argument(
        "--eccentricity-visualize-max-points",
        type=int,
        default=200_000,
        help="Maximum points shown in eccentricity visualization per tube pair.",
    )

    parser.add_argument(
        "--validate-fit-score",
        action="store_true",
        help="Run synthetic validation of rotational_fit_score() and exit.",
    )
    return parser.parse_args()


def build_config(args: argparse.Namespace) -> ReconstructionConfig:
    return ReconstructionConfig(
        dataset_dir=args.dataset_dir,
        coco_file=args.coco_file,
        start_frame=args.start_frame,
        n_frames=args.n_frames,
        save_masks=args.save_masks,
        save_point_clouds=args.save_point_clouds,
        show_preview=not args.no_preview,
        diameter_mm=args.diameter_mm,
        voxel_mm=args.voxel_mm,
        smooth_sigma_z=args.smooth_sigma_z,
        min_radius_vox=args.min_radius_vox,
        min_area_cc=args.min_area_cc,
        iou_thr=args.iou_thr,
        masks_dir=args.masks_dir,
        point_clouds_dir=args.point_clouds_dir,
        annotate_frame_parameters=args.annotate_frame_parameters,
        annotated_frames_dir=args.annotated_frames_dir,
        tracking=args.tracking or args.tracking_labels or args.preview_parameter_labels or args.annotate_frame_parameters,
        tracking_csv=args.tracking_csv,
        tracking_max_distance_mm=args.tracking_max_distance_mm,
        tracking_max_missing_frames=args.tracking_max_missing_frames,
        tracking_debug=args.tracking_debug,
        tracking_labels=args.tracking_labels,
        preview_parameter_labels=args.preview_parameter_labels,
        eccentricity=args.eccentricity or args.eccentricity_visualize or args.preview_parameter_labels or args.annotate_frame_parameters,
        parameters_dir=args.parameters_dir,
        tip_percentile=args.tip_percentile,
        eccentricity_debug=args.eccentricity_debug,
        eccentricity_visualize=args.eccentricity_visualize,
        eccentricity_visualize_every=args.eccentricity_visualize_every,
        eccentricity_visualize_max_points=args.eccentricity_visualize_max_points,
    )


def main() -> None:
    args = parse_args()

    if args.validate_fit_score:
        validate_existing_rotational_fit_score()
        return

    config = build_config(args)
    run_pipeline(config)


if __name__ == "__main__":
    main()
